/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day9plus1homeworkv2;

import static com.sun.javafx.Utils.split;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author cnp.ak
 */
public class SearchForm extends javax.swing.JFrame {

    List<ArrayObject> arrayList = new ArrayList<>();
    ArrayObject arrayObject;

    /**
     * Creates new form SearchForm
     */
    public SearchForm() {
        initComponents();

        try (BufferedReader br = new BufferedReader(new FileReader("C:\\_Development\\WorkFiles\\day9plus1\\price.txt"))) {
            String tempString;
            while ((tempString = br.readLine()) != null) {
                String priceR = "";
                String priceO = "";
                String splittedString[] = tempString.split("\t");
                try {
                    for (int i = 0; i < splittedString[3].length(); i++) {
                        if (splittedString[3].charAt(i) != ' ') {
                            priceR += splittedString[3].charAt(i);
                        }
                    }
                    for (int i = 0; i < splittedString[4].length(); i++) {
                        if (splittedString[4].charAt(i) != ' ') {
                            priceO += splittedString[4].charAt(i);
                        }
                    }
                } catch (Exception priceSpaceRemover) {
                }

                try {
                    arrayObject = new ArrayObject(
                            Integer.parseInt(splittedString[1]),
                            splittedString[2],
                            Integer.parseInt(splittedString[3]),
                            Integer.parseInt(splittedString[4]),
                            splittedString[5]);
                    arrayList.add(arrayObject);
                } catch (Exception outStringTry) {
                }
            }
        } catch (Exception readFromFileException) {
        }

//        System.out.println(arrayList.get(1).description);
//        for (ArrayObject oneItem : arrayList) {
//            System.out.println();
//        }
//        for (int i = 0; i < arrayList.size(); i++) {
//            System.out.println(arrayList.get(i).id+arrayList.get(i).description+arrayList.get(i).priceO);
//        }
//        }
//        for (int i = 0; i < arrayList.size(); i++) {
//            System.out.println(arrayList.get(i).id+arrayList.get(i).description+arrayList.get(i).priceO);
//        }
//        for (int i = 0; i < arrayList.size(); i++) {
//            System.out.println(arrayList.get(i).id +" "+ arrayList.get(i).description +" "+ arrayList.get(i).priceR+" "+arrayList.get(i).priceO+" "+arrayList.get(i).warranty);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        textField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textField.setText("jTextField1");

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(45, 45, 45)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String searchItem = textField.getText();

        for (int i = 0; i < arrayList.size(); i++) {
//            if (arrayList.get(i).description.indexOf(searchItem)!=-1){
//                label.setText(label.getText() + arrayList.get(i).id + " " + arrayList.get(i).description + " " + arrayList.get(i).priceR + " " + arrayList.get(i).priceO + " " + arrayList.get(i).warranty);
//            }

            if (arrayList.get(i).description.toLowerCase().indexOf(searchItem.toLowerCase()) != -1) {
                label.setText(label.getText() + arrayList.get(i).id + " " + arrayList.get(i).description + " " + arrayList.get(i).priceR + " " + arrayList.get(i).priceO + " " + arrayList.get(i).warranty);
            }

            //System.out.println(arrayList.get(i).id + " " + arrayList.get(i).description + " " + arrayList.get(i).priceR + " " + arrayList.get(i).priceO + " " + arrayList.get(i).warranty);
            //label.setText(label.getText()+arrayList.get(i).id + " " + arrayList.get(i).description + " " + arrayList.get(i).priceR + " " + arrayList.get(i).priceO + " " + arrayList.get(i).warranty);
            //label.setText(label.getText() + arrayList.get(i).id + " " + arrayList.get(i).description + " " + arrayList.get(i).priceR + " " + arrayList.get(i).priceO + " " + arrayList.get(i).warranty);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel label;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
