/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day2class;

/**
 *
 * @author Amilo
 */
public class calculator extends javax.swing.JFrame {

    /**
     * Creates new form calculator
     */
    public calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputVar = new javax.swing.JTextField();
        actionPlus = new javax.swing.JButton();
        actionMinus = new javax.swing.JButton();
        actionDiv = new javax.swing.JButton();
        actionMult = new javax.swing.JButton();
        buttonEq = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputVar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputVarMouseClicked(evt);
            }
        });

        actionPlus.setText("+");
        actionPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actionPlusMouseClicked(evt);
            }
        });

        actionMinus.setText("-");
        actionMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actionMinusMouseClicked(evt);
            }
        });

        actionDiv.setText("/");
        actionDiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actionDivMouseClicked(evt);
            }
        });

        actionMult.setText("*");
        actionMult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actionMultMouseClicked(evt);
            }
        });

        buttonEq.setText("=");
        buttonEq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEqMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputVar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(actionPlus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actionMinus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actionMult)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actionDiv)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonEq, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actionPlus)
                    .addComponent(actionMinus)
                    .addComponent(actionDiv)
                    .addComponent(actionMult))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonEq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    double result=0;
    double a=0;
    double b=0;
    int action=0; //1=plus, 2=minus, 3=mult, 4=divide
    
    private void actionPlusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actionPlusMouseClicked
        // TODO add your handling code here:
        if(action != 0){
            action=1;
        } else {        
            try{
                String inputString = inputVar.getText();
                a = Double.parseDouble(inputString);
                inputVar.setText("");
                action=1;
            }catch(Exception e){
                System.out.println("Err " + e.toString());
                inputVar.setText("Только числа");
            }
        }
        
    }//GEN-LAST:event_actionPlusMouseClicked

    private void actionMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actionMinusMouseClicked
        if(action != 0){
            action=2;
        } else {        
            String inputString = inputVar.getText();
            a=Double.parseDouble(inputString);
            inputVar.setText("");
            action=2;
        }
    }//GEN-LAST:event_actionMinusMouseClicked

    private void actionMultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actionMultMouseClicked
        if(action != 0){
            action=3;
        } else {        
            String inputString = inputVar.getText();
            a=Double.parseDouble(inputString);
            inputVar.setText("");
            action=3;
        }
    }//GEN-LAST:event_actionMultMouseClicked

    private void actionDivMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actionDivMouseClicked
        if(action != 0){
            action=4;
        } else {        
            String inputString = inputVar.getText();
            a=Double.parseDouble(inputString);
            inputVar.setText("");
            action=4;
        }
    }//GEN-LAST:event_actionDivMouseClicked

    private void buttonEqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEqMouseClicked
        // TODO add your handling code here:
        if(action == 0) return;
        b=Double.parseDouble(inputVar.getText());
        inputVar.setText("");
        if (action==1){
            result=a+b;
        } else if (action==2){
            result=a-b;
        } else if (action==3){
            result=a*b;
        } else {
            result=a/b;
        }
        inputVar.setText(""+result);
        action=0;
    }//GEN-LAST:event_buttonEqMouseClicked

    private void inputVarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputVarMouseClicked
        // TODO add your handling code here:
        try{
            double b = Double.parseDouble(this.inputVar.getText());
        }catch(Exception e){
            this.inputVar.setText("");    
        }
        
    }//GEN-LAST:event_inputVarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actionDiv;
    private javax.swing.JButton actionMinus;
    private javax.swing.JButton actionMult;
    private javax.swing.JButton actionPlus;
    private javax.swing.JButton buttonEq;
    private javax.swing.JTextField inputVar;
    // End of variables declaration//GEN-END:variables
}


