/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day5;

import java.util.Random;

/**
 *
 * @author Amilo
 */
public class ArrayRand extends javax.swing.JFrame {
int a[][]=new int [10][10];
Random rand = new Random();
int jsum;
int isum;
String itotal="";
    /**
     * Creates new form array2
     */
    public ArrayRand() {
        initComponents();
        for (int i=0;i<10;i++){
            jsum=0;
//            itotal=itotal+isum+" ";
//            isum=0;
            for (int j=0;j<10;j++){
                a[i][j]=rand.nextInt(3);
                System.out.print(a[i][j]+" ");
                jsum=jsum+a[i][j];  
//                isum=isum+a[j][i];
            }
            System.out.print(" :"+jsum);
//            System.out.print(" !"+isum);
            System.out.println();
        }
//         System.out.println(itotal);
               
   /**     for (int i=0;i<10;i++){
            isum=0;
            for (int j=0;j<10;j++){
                isum=isum+a[j][i];
            }
            System.out.print(" :"+isum);
        }*/ 
         
        int n=7;
        int m=7;
        
     /**   for (int i=n;i<n+4;i++){
            for (int j=m;j<m+4;j++){
                isum=isum+a[j][i];
            }
        }
         System.out.print(" :"+isum);
        */ 
        int o=20;
        if (n+o<a.length && m+o<a[0].length ){
        for (int i=n;i<n+o;i++){
            for (int j=m;j<m+o;j++){
                isum=isum+a[j][i];
            }
        }
        } else {
            for (int i=n;i<n+o;i++){
                for (int j=m;j<m+o;j++){
                    if(j < a[0].length && i<a.length){
                        isum=isum+a[j][i];
                    }
                }
            }
        }
                System.out.print(" :"+isum);
        
        
   }
 
    
        
        
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArrayRand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArrayRand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArrayRand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArrayRand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArrayRand().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
