/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day2homework;

/**
 *
 * @author Amilo
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        inputField = new javax.swing.JTextField();
        buttonClr = new javax.swing.JButton();
        buttonPlus = new javax.swing.JButton();
        buttonMinus = new javax.swing.JButton();
        buttonMult = new javax.swing.JButton();
        buttonDiv = new javax.swing.JButton();
        buttonEqu = new javax.swing.JButton();
        buttonPercent = new javax.swing.JButton();
        buttonMod = new javax.swing.JButton();
        buttonChange = new javax.swing.JButton();
        buttonRoot = new javax.swing.JButton();
        buttonDegree2 = new javax.swing.JButton();
        buttonDegree3 = new javax.swing.JButton();
        buttonDegreeXY = new javax.swing.JButton();

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setText("/");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inputField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        inputField.setText("0");
        inputField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputFieldKeyTyped(evt);
            }
        });

        buttonClr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonClr.setText("CLR");
        buttonClr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonClrMouseClicked(evt);
            }
        });

        buttonPlus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonPlus.setText("+");
        buttonPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPlusMouseClicked(evt);
            }
        });
        buttonPlus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonPlusKeyPressed(evt);
            }
        });

        buttonMinus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonMinus.setText("-");
        buttonMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMinusMouseClicked(evt);
            }
        });

        buttonMult.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonMult.setText("*");
        buttonMult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMultMouseClicked(evt);
            }
        });

        buttonDiv.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonDiv.setText("/");
        buttonDiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDivMouseClicked(evt);
            }
        });

        buttonEqu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonEqu.setText("=");
        buttonEqu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEquMouseClicked(evt);
            }
        });

        buttonPercent.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonPercent.setText("%");
        buttonPercent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPercentMouseClicked(evt);
            }
        });

        buttonMod.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonMod.setText("MOD");
        buttonMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonModMouseClicked(evt);
            }
        });

        buttonChange.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonChange.setText("+/-");
        buttonChange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonChangeMouseClicked(evt);
            }
        });

        buttonRoot.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonRoot.setText("√");
        buttonRoot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRootMouseClicked(evt);
            }
        });

        buttonDegree2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonDegree2.setText("x^2");
        buttonDegree2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDegree2MouseClicked(evt);
            }
        });

        buttonDegree3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonDegree3.setText("x^3");
        buttonDegree3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDegree3MouseClicked(evt);
            }
        });

        buttonDegreeXY.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonDegreeXY.setText("x^y");
        buttonDegreeXY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDegreeXYMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buttonDegree2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(buttonDegreeXY, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonDegree3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonPercent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonRoot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonMult, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonChange)
                            .addComponent(buttonClr)))
                    .addComponent(buttonEqu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(buttonDegree2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonDegree3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(buttonDegreeXY, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonMod, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(buttonChange, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonClr, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(buttonRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonMult, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEqu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //required variables 
    double a=0;
    double b=0;
    double result=0;
    int action=0;
    /** 0  nothing 
     * 1 +
     * 2 -
     * 3 *
     * 4 /
     * 5 root V
     * 6 %
     * 7 x^2
     * 8 x^3
     * 9 x^y
     * 10 modulus
     * 11 +/-
     * 12
     * 13
     * 14
     * 
    **/
    boolean status=true; //indicates if "a" was entered or not
    
    private void buttonClick(int action){
        try {
            a=Double.parseDouble(inputField.getText());
            status=true;
            this.action=action; //Here it is! I could apply THIS ))
            inputField.requestFocus();
            //System.out.println(""+action);
        } catch (Exception error) {
            System.out.println(""+error);
            inputField.setText("");
            inputField.requestFocus();
        } 
    }
  
    private void buttonPlusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPlusMouseClicked
        // TODO add your handling code here:
        /** try {
            a=Double.parseDouble(inputField.getText());
            status=true;
            action = 1;
            inputField.requestFocus();
        } catch (Exception error) {
            System.out.println(""+error);
            inputField.setText("");
            inputField.requestFocus();
        }
        **/
        buttonClick(1);
        //System.out.println("Action: "+action);
        //System.out.println("A is: "+a);
    }//GEN-LAST:event_buttonPlusMouseClicked

    private void buttonPlusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonPlusKeyPressed
            // TODO add your handling code here:
    }//GEN-LAST:event_buttonPlusKeyPressed

    private void inputFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputFieldKeyTyped
        if (status==true) {
            inputField.setText("");
            status=false;
        }        // TODO add your handling code here:
    }//GEN-LAST:event_inputFieldKeyTyped

    private void buttonEquMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEquMouseClicked
        try {
        b=Double.parseDouble(inputField.getText());
        if (action==1){
            result=a+b;
        }
        if (action==2){
            result=a-b;
        }
        if (action==3){
            result=a*b;
        }
        if (action==4){
            if (b==0){
                return;
            }
            result=a/b;
        }
        if (action==5){
            
        }
        if (action==6){
            
        }
        /**if (action==7){}
        if (action==8){}**/
        if (action==9){
            result=a;
            for (int i=1;i<b;i++){
                result=result*a;
                System.out.println(""+result);
            }    
        }
        if (action==10){
            result=a % b;
        }
        //if (action==11){  }
        //if (action==12){        }
        
        inputField.setText(""+result);
                
        action = 0;
        status = false;        // TODO add your handling code here:
        } catch (Exception hmm){
            return;
        }
    }//GEN-LAST:event_buttonEquMouseClicked

    private void buttonMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMinusMouseClicked
        // TODO add your handling code here:\
       buttonClick(2);
    }//GEN-LAST:event_buttonMinusMouseClicked

    private void buttonDivMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDivMouseClicked
        buttonClick(4);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDivMouseClicked

    private void buttonMultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMultMouseClicked
        buttonClick(3);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMultMouseClicked

    private void buttonDegree2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDegree2MouseClicked
        // TODO add your handling code here:
        try {
            a=Double.parseDouble(inputField.getText());
            status=false;
            this.action=0; //Here it is! I could apply THIS ))
            result=a*a;
            inputField.setText(""+result);
            inputField.requestFocus();
        } catch (Exception error) {
            System.out.println(""+error);
            inputField.setText("");
            inputField.requestFocus();
        }
    }//GEN-LAST:event_buttonDegree2MouseClicked

    private void buttonDegree3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDegree3MouseClicked
            try {
            a=Double.parseDouble(inputField.getText());
            status=false;
            this.action=0; //Here it is! I could apply THIS ))
            result=a*a*a;
            inputField.setText(""+result);
            inputField.requestFocus();
        } catch (Exception error) {
            System.out.println(""+error);
            inputField.setText("");
            inputField.requestFocus();
        }    // TODO add your handling code here:
    }//GEN-LAST:event_buttonDegree3MouseClicked

    private void buttonDegreeXYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDegreeXYMouseClicked
         buttonClick(9);// TODO add your handling code here:
    }//GEN-LAST:event_buttonDegreeXYMouseClicked

    private void buttonClrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClrMouseClicked
    double a=0;
    double b=0;
    double result=0;
    int action=0;
    status=true;
    inputField.setText("0");// TODO add your handling code here:
    inputField.requestFocus();
    }//GEN-LAST:event_buttonClrMouseClicked

    private void buttonModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonModMouseClicked
         buttonClick(10);// TODO add your handling code here:
    }//GEN-LAST:event_buttonModMouseClicked

    private void buttonChangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonChangeMouseClicked
        try {
            a=Double.parseDouble(inputField.getText());
            status=false;
            this.action=0; //Here it is! I could apply THIS ))
            result=a*(-1.0);
            inputField.setText(""+result);
            inputField.requestFocus();
        } catch (Exception error) {
            System.out.println(""+error);
            inputField.setText("");
            inputField.requestFocus();
        }
    }//GEN-LAST:event_buttonChangeMouseClicked

    private void buttonPercentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPercentMouseClicked
        b=Double.parseDouble(inputField.getText());
        double percentResult=a*(b/100);
        b=percentResult;
        inputField.setText(""+b);
    }//GEN-LAST:event_buttonPercentMouseClicked

    private void buttonRootMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRootMouseClicked
        try {
            a=Double.parseDouble(inputField.getText());
            status=false;
            this.action=0; //Here it is! I could apply THIS ))
            result=Math.sqrt(a);
            inputField.setText(""+result);
            inputField.requestFocus();
        } catch (Exception error) {
            System.out.println(""+error);
            inputField.setText("");
            inputField.requestFocus();
        }// TODO add your handling code here:
    }//GEN-LAST:event_buttonRootMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonChange;
    private javax.swing.JButton buttonClr;
    private javax.swing.JButton buttonDegree2;
    private javax.swing.JButton buttonDegree3;
    private javax.swing.JButton buttonDegreeXY;
    private javax.swing.JButton buttonDiv;
    private javax.swing.JButton buttonEqu;
    private javax.swing.JButton buttonMinus;
    private javax.swing.JButton buttonMod;
    private javax.swing.JButton buttonMult;
    private javax.swing.JButton buttonPercent;
    private javax.swing.JButton buttonPlus;
    private javax.swing.JButton buttonRoot;
    private javax.swing.JTextField inputField;
    private javax.swing.JButton jButton7;
    // End of variables declaration//GEN-END:variables
}
